name: pp_tool
description: Automatically and quickly generate custom Flutter template project.
version: 1.0.0
repository: https://github.com/xiaopindev/pp_tool

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.6.0
  archive: ^3.6.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
